# Generated by Django 4.1.2 on 2022-10-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ships',
            options={'ordering': ['title'], 'verbose_name': 'Spaceships', 'verbose_name_plural': 'Spaceships'},
        ),
    ]
